---
- name: Erstelle eine Ubuntu-VM auf vSphere
  hosts: localhost
  become: false
  #gather_facts: false
  collections:
    - community.vmware
  #pre_tasks:
  #  - include_vars: vars.yml
  tasks:
  - name: Lade Ubuntu-ISO-Image herunter
    get_url:
      url: "{{ ubuntu_iso_url }}"
      dest: "{{ ubuntu_iso_local_path }}"
  
  - name: Erstelle virtuelle Maschine
    vmware_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      cluster: "{{ vcenter_cluster }}"
      datastore: "{{ vcenter_datastore }}"
      name: "{{ vm_name }}"
      folder: "/"
      hardware:
        num_cpus: "{{ vm_cpus }}"
        memory_mb: "{{ vm_memory_mb }}"
        scsi: paravirtual
        disk:
        - size_gb: "{{ vm_disk_size_gb }}"
          type: thin
      networks:
      - name: "{{ vm_network_name }}"
        start_connected: yes
        switch_type: standard
      state: poweredoff
  
  - name: Konfiguriere virtuelle Maschine
    vmware_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      name: "{{ vm_name }}"
      folder: "/"
      guest_id: ubuntu64Guest
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        devices:
        - cdrom:
            iso_path: "{{ ubuntu_iso_local_path }}"
            start_connected: yes
            type: client
      state: poweredon
    register: vm_info
  
  - name: Warte, bis die virtuelle Maschine gestartet ist
    local_action:
      module: wait_for
      timeout: 300
      host: "{{ vm_info.instance.hostname }}"
      port: 22
      state: started
  
  - name: Warte, bis die SSH-Verbindung verfügbar ist
    local_action:
      module: wait_for
      timeout: 60
      host: "{{ vm_info.instance.ip_address }}"
      port: 22
      state: started
  
  - name: Warte, bis das Betriebssystem bootet
    local_action:
      module: wait_for
      timeout: 300
      host: "{{ vm_info.instance.ip_address }}"
      port: 22
