---
- name: read file on host
  hosts: all
  vars:
    contents: "{{ lookup('file','/etc/hosts') }}"
    tasks:
      - name: print file
        ansible.builtin.debug:
          msg: "the content of file is {{ contents }}"