---
- name: blockinfile module demo
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Generate /etc/hosts file
      ansible.builtin.blockinfile:
        state: present
        dest: /etc/hosts
        content: |
          192.168.100.1 demo demo.example.com